# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import lingjing_pb2 as lingjing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lingjing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """──── 核心服务: 记忆引擎 ────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/lingjing.v1.MemoryService/Remember',
                request_serializer=lingjing__pb2.RememberRequest.SerializeToString,
                response_deserializer=lingjing__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/lingjing.v1.MemoryService/Recall',
                request_serializer=lingjing__pb2.RecallRequest.SerializeToString,
                response_deserializer=lingjing__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/lingjing.v1.MemoryService/Forget',
                request_serializer=lingjing__pb2.ForgetRequest.SerializeToString,
                response_deserializer=lingjing__pb2.ForgetResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/lingjing.v1.MemoryService/Stats',
                request_serializer=lingjing__pb2.StatsRequest.SerializeToString,
                response_deserializer=lingjing__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Classify = channel.unary_unary(
                '/lingjing.v1.MemoryService/Classify',
                request_serializer=lingjing__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=lingjing__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.ExtractKnowledge = channel.unary_unary(
                '/lingjing.v1.MemoryService/ExtractKnowledge',
                request_serializer=lingjing__pb2.ExtractKnowledgeRequest.SerializeToString,
                response_deserializer=lingjing__pb2.ExtractKnowledgeResponse.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_unary(
                '/lingjing.v1.MemoryService/Summarize',
                request_serializer=lingjing__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=lingjing__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/lingjing.v1.MemoryService/SemanticSearch',
                request_serializer=lingjing__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=lingjing__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lingjing.v1.MemoryService/Health',
                request_serializer=lingjing__pb2.HealthRequest.SerializeToString,
                response_deserializer=lingjing__pb2.HealthResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """──── 核心服务: 记忆引擎 ────

    """

    def Remember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=lingjing__pb2.RememberRequest.FromString,
                    response_serializer=lingjing__pb2.RememberResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=lingjing__pb2.RecallRequest.FromString,
                    response_serializer=lingjing__pb2.RecallResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=lingjing__pb2.ForgetRequest.FromString,
                    response_serializer=lingjing__pb2.ForgetResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=lingjing__pb2.StatsRequest.FromString,
                    response_serializer=lingjing__pb2.StatsResponse.SerializeToString,
            ),
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=lingjing__pb2.ClassifyRequest.FromString,
                    response_serializer=lingjing__pb2.ClassifyResponse.SerializeToString,
            ),
            'ExtractKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractKnowledge,
                    request_deserializer=lingjing__pb2.ExtractKnowledgeRequest.FromString,
                    response_serializer=lingjing__pb2.ExtractKnowledgeResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=lingjing__pb2.SummarizeRequest.FromString,
                    response_serializer=lingjing__pb2.SummarizeResponse.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=lingjing__pb2.SemanticSearchRequest.FromString,
                    response_serializer=lingjing__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lingjing__pb2.HealthRequest.FromString,
                    response_serializer=lingjing__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lingjing.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lingjing.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """──── 核心服务: 记忆引擎 ────

    """

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Remember',
            lingjing__pb2.RememberRequest.SerializeToString,
            lingjing__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Recall',
            lingjing__pb2.RecallRequest.SerializeToString,
            lingjing__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Forget',
            lingjing__pb2.ForgetRequest.SerializeToString,
            lingjing__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Stats',
            lingjing__pb2.StatsRequest.SerializeToString,
            lingjing__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Classify',
            lingjing__pb2.ClassifyRequest.SerializeToString,
            lingjing__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/ExtractKnowledge',
            lingjing__pb2.ExtractKnowledgeRequest.SerializeToString,
            lingjing__pb2.ExtractKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Summarize',
            lingjing__pb2.SummarizeRequest.SerializeToString,
            lingjing__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/SemanticSearch',
            lingjing__pb2.SemanticSearchRequest.SerializeToString,
            lingjing__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.MemoryService/Health',
            lingjing__pb2.HealthRequest.SerializeToString,
            lingjing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LingjingRegistryStub(object):
    """──── 服务发现: 灵境注册中心 ────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/lingjing.v1.LingjingRegistry/Register',
                request_serializer=lingjing__pb2.RegisterRequest.SerializeToString,
                response_deserializer=lingjing__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/lingjing.v1.LingjingRegistry/Heartbeat',
                request_serializer=lingjing__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=lingjing__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/lingjing.v1.LingjingRegistry/Discover',
                request_serializer=lingjing__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=lingjing__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/lingjing.v1.LingjingRegistry/Deregister',
                request_serializer=lingjing__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=lingjing__pb2.DeregisterResponse.FromString,
                _registered_method=True)


class LingjingRegistryServicer(object):
    """──── 服务发现: 灵境注册中心 ────

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LingjingRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=lingjing__pb2.RegisterRequest.FromString,
                    response_serializer=lingjing__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=lingjing__pb2.HeartbeatRequest.FromString,
                    response_serializer=lingjing__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=lingjing__pb2.DiscoverRequest.FromString,
                    response_serializer=lingjing__pb2.DiscoverResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=lingjing__pb2.DeregisterRequest.FromString,
                    response_serializer=lingjing__pb2.DeregisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lingjing.v1.LingjingRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lingjing.v1.LingjingRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LingjingRegistry(object):
    """──── 服务发现: 灵境注册中心 ────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.LingjingRegistry/Register',
            lingjing__pb2.RegisterRequest.SerializeToString,
            lingjing__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.LingjingRegistry/Heartbeat',
            lingjing__pb2.HeartbeatRequest.SerializeToString,
            lingjing__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.LingjingRegistry/Discover',
            lingjing__pb2.DiscoverRequest.SerializeToString,
            lingjing__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.LingjingRegistry/Deregister',
            lingjing__pb2.DeregisterRequest.SerializeToString,
            lingjing__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LingjingEventBusStub(object):
    """──── 事件总线 ────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/lingjing.v1.LingjingEventBus/Publish',
                request_serializer=lingjing__pb2.PublishRequest.SerializeToString,
                response_deserializer=lingjing__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.stream_stream(
                '/lingjing.v1.LingjingEventBus/Subscribe',
                request_serializer=lingjing__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=lingjing__pb2.BusEvent.FromString,
                _registered_method=True)


class LingjingEventBusServicer(object):
    """──── 事件总线 ────

    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LingjingEventBusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=lingjing__pb2.PublishRequest.FromString,
                    response_serializer=lingjing__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=lingjing__pb2.SubscribeRequest.FromString,
                    response_serializer=lingjing__pb2.BusEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lingjing.v1.LingjingEventBus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lingjing.v1.LingjingEventBus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LingjingEventBus(object):
    """──── 事件总线 ────

    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.LingjingEventBus/Publish',
            lingjing__pb2.PublishRequest.SerializeToString,
            lingjing__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lingjing.v1.LingjingEventBus/Subscribe',
            lingjing__pb2.SubscribeRequest.SerializeToString,
            lingjing__pb2.BusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """──── Agent调度 ────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dispatch = channel.unary_unary(
                '/lingjing.v1.AgentService/Dispatch',
                request_serializer=lingjing__pb2.DispatchRequest.SerializeToString,
                response_deserializer=lingjing__pb2.DispatchResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/lingjing.v1.AgentService/GetStatus',
                request_serializer=lingjing__pb2.AgentStatusRequest.SerializeToString,
                response_deserializer=lingjing__pb2.AgentStatusResponse.FromString,
                _registered_method=True)
        self.ListCapabilities = channel.unary_unary(
                '/lingjing.v1.AgentService/ListCapabilities',
                request_serializer=lingjing__pb2.ListCapabilitiesRequest.SerializeToString,
                response_deserializer=lingjing__pb2.ListCapabilitiesResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """──── Agent调度 ────

    """

    def Dispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=lingjing__pb2.DispatchRequest.FromString,
                    response_serializer=lingjing__pb2.DispatchResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=lingjing__pb2.AgentStatusRequest.FromString,
                    response_serializer=lingjing__pb2.AgentStatusResponse.SerializeToString,
            ),
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=lingjing__pb2.ListCapabilitiesRequest.FromString,
                    response_serializer=lingjing__pb2.ListCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lingjing.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lingjing.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """──── Agent调度 ────

    """

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.AgentService/Dispatch',
            lingjing__pb2.DispatchRequest.SerializeToString,
            lingjing__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.AgentService/GetStatus',
            lingjing__pb2.AgentStatusRequest.SerializeToString,
            lingjing__pb2.AgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lingjing.v1.AgentService/ListCapabilities',
            lingjing__pb2.ListCapabilitiesRequest.SerializeToString,
            lingjing__pb2.ListCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
