# -*- coding: utf-8-sig -*-
"""enforcement_gi_ModuleEvolutionSpec — 模块进化规格 (SSS-PhaseE合并精简)

保留独立文件: 699行含大量数据，超过基点300行阈值
导入源: enforcement_gi_models.py (SSS-PhaseE合并后)
"""
from dataclasses import dataclass, field
from typing import List
from .enforcement_gi_models import ImpactTier, ModuleImpact


@dataclass
class ModuleEvolutionSpec:
    """模块进化规格 — 天机v9.1全系统51模块进化目标总表"""

    module_name: str
    tier: ImpactTier
    composite: float
    evolution_targets: List[str]
    estimated_effort_hours: float = 0.0
    risk_level: str = "low"
    standard_alignment: List[str] = field(default_factory=list)
    consumer_impacts: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "module": self.module_name,
            "tier": self.tier.value,
            "composite": self.composite,
            "targets": self.evolution_targets,
            "effort_hours": self.estimated_effort_hours,
            "risk": self.risk_level,
            "standards": self.standard_alignment,
            "consumers": self.consumer_impacts,
        }


GLOBAL_IMPACT_MATRIX: List[ModuleImpact] = [
    # ═══════════════════════════════════════════
    # S级 (>=0.80): 核心基础设施 — 对话录入直接影响
    # ═══════════════════════════════════════════
    ModuleImpact(
        "enforcement_hook",
        "core/enforcement_hook.py",
        ImpactTier.S,
        1.00,
        0.95,
        0.95,
        0.95,
        dimensions=["直接影响", "记忆存储链", "学习进化链"],
        evolution_targets=[
            "ConversationRecord字段",
            "_nudge_decide阈值",
            "_classify_conversation权重",
            "_annotate_iso_dialogue_acts规则",
            "_track_token_economy公式",
            "_generate_fair_metadata模板",
            "_detect_agent_switches模式",
            "ConversationRegistry缓存策略",
        ],
        impact_description="对话录入核心，23字段ConRecords直接生成于此，所有辐射的起点",
    ),
    ModuleImpact(
        "tianji_mcp_server",
        "mcp/tianji_mcp_server.py",
        ImpactTier.S,
        0.95,
        0.90,
        0.90,
        0.90,
        dimensions=["直接影响", "智能调度链"],
        evolution_targets=[
            "MCP拦截策略",
            "handle_tools_call记录粒度",
            "session_id自动注入",
        ],
        impact_description="MCP工具调用拦截器，拦截所有工具调用为录入提供细节数据",
    ),
    ModuleImpact(
        "quality_gate",
        "core/quality_gate.py",
        ImpactTier.S,
        0.85,
        0.90,
        0.90,
        0.85,
        dimensions=["直接影响", "记忆存储链"],
        evolution_targets=["min_value_score阈值", "max_similarity阈值", "三问推演规则"],
        impact_description="QualityGate v5.0决定每条录入是否通过/降级/拒绝，直接影响录入成功率",
    ),
    # ═══════════════════════════════════════════
    # A级 (>=0.60): 关键链路 — 数据流经关键节点
    # ═══════════════════════════════════════════
    ModuleImpact(
        "engine",
        "core/engine.py",
        ImpactTier.A,
        0.80,
        0.85,
        0.70,
        0.95,
        dimensions=["记忆存储链"],
        evolution_targets=["ICME六层写入性能", "记忆固结间隔", "容量分配策略"],
        impact_description="ICME核心引擎v5.3，六层记忆的写入/检索/固结中枢",
    ),
    ModuleImpact(
        "hybrid_engine",
        "core/hybrid_engine.py",
        ImpactTier.A,
        0.70,
        0.85,
        0.65,
        0.85,
        dimensions=["记忆存储链"],
        evolution_targets=["SQLite+JSON混合存储策略", "写入批量化"],
        impact_description="SQLite+JSON混合存储，对话记录持久化的物理层",
    ),
    ModuleImpact(
        "sqlite_store",
        "core/sqlite_store.py",
        ImpactTier.A,
        0.65,
        0.85,
        0.60,
        0.80,
        dimensions=["记忆存储链"],
        evolution_targets=["FTS5索引策略", "WAL并发优化"],
        impact_description="FTS5全文搜索+WAL并发，对话内容可检索性的基石",
    ),
    ModuleImpact(
        "deepseek_driver",
        "core/deepseek_driver.py",
        ImpactTier.A,
        0.75,
        0.70,
        0.80,
        0.85,
        dimensions=["学习进化链", "直接影响"],
        evolution_targets=[
            "三循环并行参数",
            "TraeConversationCapture捕获频率",
            "决策质量评估",
        ],
        impact_description="DeepSeek驾驶者v2.0，三循环决策驱动，对话捕获+记忆决策的双重角色",
    ),
    ModuleImpact(
        "models",
        "core/models.py",
        ImpactTier.A,
        0.60,
        0.80,
        0.75,
        0.80,
        dimensions=["直接影响"],
        evolution_targets=["Pydantic数据模型", "ConversationRecord序列化规范"],
        impact_description="Pydantic数据模型定义，ConversationRecord结构和验证的基础",
    ),
    ModuleImpact(
        "conversation_engine",
        "core/conversation_engine.py",
        ImpactTier.A,
        0.85,
        0.75,
        0.70,
        0.70,
        dimensions=["直接影响", "智能调度链"],
        evolution_targets=["对话流转引擎", "上下文窗口管理"],
        impact_description="对话引擎，直接管理对话流转和上下文窗口",
    ),
    ModuleImpact(
        "config",
        "core/config.py",
        ImpactTier.A,
        0.50,
        0.65,
        0.65,
        0.90,
        dimensions=["直接影响"],
        evolution_targets=["ICMEConfig v8.0参数", "容量上限值"],
        impact_description="ICMEConfig v8.0，六层容量上限/固结间隔等全局配置",
    ),
    ModuleImpact(
        "enforcement/mcp_bridge",
        "core/enforcement/mcp_bridge.py",
        ImpactTier.A,
        0.80,
        0.70,
        0.75,
        0.70,
        dimensions=["直接影响", "智能调度链"],
        evolution_targets=["MCP桥接方法集", "register_*系列方法扩展"],
        impact_description="MCP桥接器，连接enforcement_hook和MCP Server的双向通道",
    ),
    # ═══════════════════════════════════════════
    # B级 (>=0.40): 重要依存 — 间接受影响
    # ═══════════════════════════════════════════
    ModuleImpact(
        "learning_loop",
        "core/learning_loop.py",
        ImpactTier.B,
        0.55,
        0.55,
        0.70,
        0.70,
        dimensions=["学习进化链"],
        evolution_targets=["闭环学习触发周期", "Skill提炼阈值", "反思周期"],
        impact_description="闭环学习引擎，从录入内容中提炼Skill和经验",
    ),
    ModuleImpact(
        "evolution_loop",
        "core/evolution_loop.py",
        ImpactTier.B,
        0.50,
        0.50,
        0.75,
        0.70,
        dimensions=["学习进化链"],
        evolution_targets=[
            "OBSERVE→LEARN→EVOLVE周期",
            "Urgency公式",
            "EffectWatchdog阈值",
        ],
        impact_description="进化闭环协议，录入质量下降时触发进化信号",
    ),
    ModuleImpact(
        "evolution_engine",
        "core/evolution_engine.py",
        ImpactTier.B,
        0.45,
        0.45,
        0.85,
        0.70,
        dimensions=["学习进化链"],
        evolution_targets=["三级自修改参数", "规则增补策略", "架构演化条件"],
        impact_description="三级自修改引擎，参数调优→规则增补→架构演化",
    ),
    ModuleImpact(
        "evolution_bus",
        "core/evolution_bus.py",
        ImpactTier.B,
        0.40,
        0.45,
        0.70,
        0.65,
        dimensions=["学习进化链"],
        evolution_targets=["进化信号路由", "ROUTING_TABLE自适应", "signal_history窗口"],
        impact_description="进化总线，录入异常信号跨模块广播和联动",
    ),
    ModuleImpact(
        "knowledge_extractor",
        "core/knowledge_extractor.py",
        ImpactTier.B,
        0.50,
        0.55,
        0.65,
        0.60,
        dimensions=["知识抽取链"],
        evolution_targets=["知识三元组抽取规则", "实体识别准确率"],
        impact_description="知识抽取器，从录入内容中提取(主体-关系-客体)三元组",
    ),
    ModuleImpact(
        "llm_bridge",
        "core/llm_bridge.py",
        ImpactTier.B,
        0.55,
        0.50,
        0.60,
        0.70,
        dimensions=["知识抽取链", "直接录入"],
        evolution_targets=["DeepSeek注入参数", "remember/recall接口优化"],
        impact_description="LLM桥接，DeepSeekremember()/recall()双注入",
    ),
    ModuleImpact(
        "llm_kg_enhancer",
        "core/llm_kg_enhancer.py",
        ImpactTier.B,
        0.40,
        0.45,
        0.60,
        0.55,
        dimensions=["知识抽取链"],
        evolution_targets=["知识图谱增强规则", "LLM增强策略"],
        impact_description="知识图谱增强器，用LLM增强录入内容的知识抽取质量",
    ),
    ModuleImpact(
        "kg_sync_hook",
        "core/kg_sync_hook.py",
        ImpactTier.B,
        0.45,
        0.40,
        0.55,
        0.50,
        dimensions=["知识抽取链"],
        evolution_targets=["知识图谱同步频率", "冲突检测规则"],
        impact_description="知识图谱同步钩子，录入内容→知识图谱实时同步",
    ),
    ModuleImpact(
        "adaptive_retriever",
        "core/adaptive_retriever.py",
        ImpactTier.B,
        0.35,
        0.50,
        0.55,
        0.60,
        dimensions=["记忆存储链"],
        evolution_targets=["检索策略自适应", "检索权重调优"],
        impact_description="自适应检索器，录入内容→检索策略自适应优化",
    ),
    ModuleImpact(
        "hybrid_retriever",
        "core/hybrid_retriever.py",
        ImpactTier.B,
        0.35,
        0.50,
        0.50,
        0.55,
        dimensions=["记忆存储链"],
        evolution_targets=["混合检索融合权重", "FTS5+向量检索比例"],
        impact_description="混合检索器，全文+语义双路检索融合",
    ),
    ModuleImpact(
        "preference_learner",
        "core/preference_learner.py",
        ImpactTier.B,
        0.45,
        0.40,
        0.55,
        0.50,
        dimensions=["学习进化链"],
        evolution_targets=["用户偏好学习模型", "偏好置信度阈值"],
        impact_description="偏好学习器，从录入对话中学习用户偏好模式",
    ),
    ModuleImpact(
        "skill_learner",
        "core/skill_learner.py",
        ImpactTier.B,
        0.40,
        0.40,
        0.55,
        0.50,
        dimensions=["学习进化链"],
        evolution_targets=["Skill自动生成规则", "Skill复用触发条件"],
        impact_description="技能学习器，从成功录入案例中自动提炼Skill",
    ),
    ModuleImpact(
        "skill_registry",
        "core/skill_registry.py",
        ImpactTier.B,
        0.35,
        0.35,
        0.45,
        0.60,
        dimensions=["智能调度链"],
        evolution_targets=["Skill注册策略", "discover扫描频率"],
        impact_description="技能注册表，录入产生的Skill自动注册和管理",
    ),
    ModuleImpact(
        "agent_orchestrator",
        "core/agent_orchestrator.py",
        ImpactTier.B,
        0.55,
        0.50,
        0.65,
        0.70,
        dimensions=["智能调度链"],
        evolution_targets=["Agent编排策略", "长链流水线优化", "并行分析调度"],
        impact_description="Agent编排器，18Agent调度，录入内容提供决策上下文",
    ),
    ModuleImpact(
        "intelligent_scheduler",
        "core/intelligent_scheduler.py",
        ImpactTier.B,
        0.50,
        0.45,
        0.60,
        0.65,
        dimensions=["智能调度链"],
        evolution_targets=["调度优先级算法", "负载均衡策略"],
        impact_description="智能调度器，任务分解和资源分配",
    ),
    ModuleImpact(
        "tvp_bridge",
        "core/tvp_bridge.py",
        ImpactTier.B,
        0.60,
        0.50,
        0.55,
        0.55,
        dimensions=["智能调度链", "直接影响"],
        evolution_targets=["TVP声明格式", "Agent切换追踪粒度"],
        impact_description="TVP透明调度桥接，Agent切换记录→录入数据源",
    ),
    ModuleImpact(
        "message_gateway",
        "core/message_gateway.py",
        ImpactTier.B,
        0.45,
        0.45,
        0.45,
        0.55,
        dimensions=["智能调度链"],
        evolution_targets=["多平台消息路由", "统一网关格式"],
        impact_description="多平台统一网关，多入口对话统一接入录入",
    ),
    ModuleImpact(
        "workflow_engine",
        "core/workflow_engine.py",
        ImpactTier.B,
        0.40,
        0.40,
        0.45,
        0.55,
        dimensions=["智能调度链"],
        evolution_targets=["Skill编排策略", "工作流模板库"],
        impact_description="Skill编排引擎，录入触发的自动化工作流",
    ),
    # ═══════════════════════════════════════════
    # C级 (>=0.20): 弱关联 — 可感知影响
    # ═══════════════════════════════════════════
    ModuleImpact(
        "governance_pipeline",
        "core/governance_pipeline.py",
        ImpactTier.C,
        0.35,
        0.35,
        0.40,
        0.55,
        dimensions=["治理审计链"],
        evolution_targets=["审计流水线规则", "Plan→Audit→Implement→Approve周期"],
        impact_description="治理流水线，录入内容的合规审计",
    ),
    ModuleImpact(
        "governance_orchestrator",
        "core/governance_orchestrator.py",
        ImpactTier.C,
        0.30,
        0.30,
        0.35,
        0.50,
        dimensions=["治理审计链"],
        evolution_targets=["治理编排策略", "审计触发条件"],
        impact_description="治理编排器，录入异常触发治理流程",
    ),
    ModuleImpact(
        "full_system_audit",
        "core/full_system_audit.py",
        ImpactTier.C,
        0.25,
        0.25,
        0.45,
        0.55,
        dimensions=["治理审计链"],
        evolution_targets=["全系统审计范围", "审计报告格式"],
        impact_description="全系统审计，录入质量纳入系统级审计指标",
    ),
    ModuleImpact(
        "active_memory",
        "active_memory/",
        ImpactTier.C,
        0.40,
        0.40,
        0.45,
        0.50,
        dimensions=["直接影响"],
        evolution_targets=["主动记忆推送频率", "tianji_intercept优先级"],
        impact_description="主动记忆协议，对话前主动注入历史上下文",
    ),
    ModuleImpact(
        "indexing",
        "indexing/",
        ImpactTier.C,
        0.30,
        0.50,
        0.45,
        0.55,
        dimensions=["知识抽取链"],
        evolution_targets=["语义搜索索引策略", "认知流水线阶段"],
        impact_description="语义搜索索引，录入内容→索引更新策略",
    ),
    ModuleImpact(
        "event_consumer",
        "core/event_consumer.py",
        ImpactTier.C,
        0.25,
        0.35,
        0.35,
        0.40,
        dimensions=["基础设施链"],
        evolution_targets=["事件消费优先级", "事件过滤规则"],
        impact_description="事件消费者，录入事件→系统级事件分发",
    ),
    ModuleImpact(
        "resilience",
        "core/resilience.py",
        ImpactTier.C,
        0.25,
        0.30,
        0.40,
        0.50,
        dimensions=["基础设施链"],
        evolution_targets=["降级触发条件", "恢复策略"],
        impact_description="韧性模块，录入链路的故障降级SOP",
    ),
    ModuleImpact(
        "performance_optimizer",
        "core/performance_optimizer.py",
        ImpactTier.C,
        0.25,
        0.30,
        0.35,
        0.45,
        dimensions=["基础设施链"],
        evolution_targets=["性能优化策略", "瓶颈检测阈值"],
        impact_description="性能优化器，录入吞吐量+延迟优化",
    ),
    ModuleImpact(
        "procedural_memory",
        "core/procedural_memory.py",
        ImpactTier.C,
        0.30,
        0.30,
        0.35,
        0.40,
        dimensions=["学习进化链"],
        evolution_targets=["程序记忆模板", "流程固化规则"],
        impact_description="程序记忆，录入→业务流程模板固化",
    ),
    ModuleImpact(
        "memory_state_manager",
        "core/memory_state_manager.py",
        ImpactTier.C,
        0.30,
        0.40,
        0.35,
        0.45,
        dimensions=["记忆存储链"],
        evolution_targets=["记忆状态管理", "状态转换策略"],
        impact_description="记忆状态管理器，录入内容的状态生命周期管理",
    ),
    ModuleImpact(
        "memory_dynamic_manager",
        "core/memory_dynamic_manager.py",
        ImpactTier.C,
        0.30,
        0.40,
        0.40,
        0.45,
        dimensions=["记忆存储链"],
        evolution_targets=["动态容量管理", "层间迁移策略"],
        impact_description="记忆动态管理器，录入压力下的层间迁移策略",
    ),
    # ═══════════════════════════════════════════
    # D级 (<0.20): 几乎无关
    # ═══════════════════════════════════════════
    ModuleImpact(
        "tianji_container",
        "core/tianji_container.py",
        ImpactTier.D,
        0.10,
        0.15,
        0.20,
        0.70,
        dimensions=["基础设施链"],
        evolution_targets=["容器健康检查", "模块生命周期"],
        impact_description="总控容器，间接承载录入模块的生命周期管理",
    ),
    ModuleImpact(
        "module_manager",
        "core/module_manager.py",
        ImpactTier.D,
        0.10,
        0.10,
        0.15,
        0.60,
        dimensions=["基础设施链"],
        evolution_targets=["模块加载策略"],
        impact_description="模块管理器，录入模块的加载和初始化",
    ),
    ModuleImpact(
        "namespace_manager",
        "core/namespace_manager.py",
        ImpactTier.D,
        0.05,
        0.10,
        0.10,
        0.55,
        dimensions=["基础设施链"],
        evolution_targets=["命名空间隔离"],
        impact_description="命名空间管理器，录入数据的命名空间隔离",
    ),
    ModuleImpact(
        "service_registry",
        "core/service_registry.py",
        ImpactTier.D,
        0.05,
        0.10,
        0.10,
        0.55,
        dimensions=["基础设施链"],
        evolution_targets=["服务注册策略"],
        impact_description="服务注册表，录入相关服务的注册和发现",
    ),
    ModuleImpact(
        "dao_registry",
        "core/dao_registry.py",
        ImpactTier.D,
        0.05,
        0.15,
        0.10,
        0.50,
        dimensions=["基础设施链"],
        evolution_targets=["DAO注册策略"],
        impact_description="DAO注册表，录入数据访问对象的注册管理",
    ),
    ModuleImpact(
        "stat_collector",
        "core/stat_collector.py",
        ImpactTier.D,
        0.15,
        0.20,
        0.20,
        0.40,
        dimensions=["基础设施链"],
        evolution_targets=["统计采集频率"],
        impact_description="统计收集器，录入数量/质量的统计指标",
    ),
    # ═══════════════════════════════════════════
    # API层辐射 (C级为主)
    # ═══════════════════════════════════════════
    ModuleImpact(
        "memory_routes",
        "server/api/memory_routes.py",
        ImpactTier.C,
        0.40,
        0.50,
        0.40,
        0.60,
        dimensions=["API暴露链"],
        evolution_targets=["/api/memory CRUD端点", "批量写入接口"],
        impact_description="记忆API路由，对话记录的REST入口",
    ),
    ModuleImpact(
        "enforcement_routes",
        "server/api/enforcement_routes.py",
        ImpactTier.C,
        0.45,
        0.45,
        0.50,
        0.50,
        dimensions=["API暴露链"],
        evolution_targets=["强制执行API端点", "进化状态查询接口"],
        impact_description="强制执行API路由，录入状态的REST查询入口",
    ),
    ModuleImpact(
        "search_routes",
        "server/api/search_routes.py",
        ImpactTier.C,
        0.30,
        0.45,
        0.35,
        0.55,
        dimensions=["API暴露链"],
        evolution_targets=["语义搜索API", "跨层检索端点"],
        impact_description="搜索API路由，录入内容的检索入口",
    ),
    ModuleImpact(
        "summary_routes",
        "server/api/summary_routes.py",
        ImpactTier.C,
        0.35,
        0.40,
        0.35,
        0.45,
        dimensions=["API暴露链"],
        evolution_targets=["会话摘要API"],
        impact_description="摘要API路由，录入会话的摘要生成",
    ),
    ModuleImpact(
        "active_routes",
        "server/api/active_routes.py",
        ImpactTier.C,
        0.35,
        0.40,
        0.40,
        0.45,
        dimensions=["API暴露链"],
        evolution_targets=["主动记录API", "tianji_intercept端点"],
        impact_description="主动记忆API路由，tianji_intercept入口",
    ),
]




__all__ = ["ImpactTier", "ImpactDimension", "ModuleImpact", "SubWeightDetail", "WeightBreakdown", "StandardGap", "ConsumerDemand", "ModuleEvolutionSpec"]


__all__ = ["ModuleEvolutionSpec"]
